version: '3.9'

services:
  snapclient:
    image: ghcr.io/shuricksumy/ledfx-snapcast-docker:latest
    container_name: snapclient_dx5
    restart: unless-stopped
    devices:
      - "/dev/snd:/dev/snd" # Access hardware cards
    environment:
      - ROLE=client
      - HOST=192.168.111.111
      - SOUND_BACKEND=alsa
      - ALSA_DEVICE=hw:DX5
      - CLIENT_ID=DX5-SNAP
      # - EXTRA_ARGS=--sampleformat 48000:24:*
    networks:
      - default
      - npm_proxy