version: '3.9'
services:
  ledfx:
    image: ghcr.io/shuricksumy/ledfx-snapcast-docker:latest
    container_name: ledfx_visualizer
    restart: unless-stopped
    privileged: true      # Required for the script to start D-Bus/Avahi
    ports:
      - "8888:8888"       # LedFx Web UI
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - ROLE=ledfx
      - LOOPBACK_NUMBER=10
     #- EXTRA_ARGS=--some-arg value
    networks:
      - default
      - npm_proxy